test:
  adapter: sqlite3
  database: osoanyi_test.db
  pool: 5
  timeout: 5000
  host: localhost
  encoding: unicode

development:
  adapter: postgresql
  database: osoanyi_dev
  encoding: unicode
  host: localhost

production:
  adapter: postgresql
  database: osoanyi_prod
  host: localhost
  encoding: unicode
