# http://stackoverflow.com/questions/5821238/rake-dbcreate-encoding-error-with-postgresql
test:
  adapter: sqlite3
  database: osoanyi_test.db
  pool: 5
  timeout: 5000
  host: localhost
  encoding: unicode
  template: template0

development:
  adapter: postgresql
  database: osoanyi_dev
  encoding: unicode
  template: template0
  host: localhost

production:
  adapter: postgresql
  database: osoanyi_prod
  host: localhost
  encoding: unicode
  template: template0
